[package]
name = "innit"
version = "0.1.0"
authors = ["Michael Wagner <wagner.mchl@googlemail.com>"]

[dependencies]
log = "0.4"
pretty_env_logger = "0.3"
rand = "0.7.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tcod = { version = "0.15.0", features = ["serialization"] }
typetag = "0.1"
