[package]
name = "innit"
version = "0.1.0"
authors = ["Michael Wagner <wagner.mchl@googlemail.com>"]

[dependencies]
tcod = { version = "0.15.0", features = ["serialization"] }
rand = "0.7.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
typetag = "0.1"
