[package]
name = "innit"
version = "0.0.1"
authors = ["Michael Wagner <wagner.mchl@googlemail.com>"]
license = "MIT License"
edition = "2018"

[dependencies]
log = "0.4"
num = "0.2"
pretty_env_logger = "0.4.0"
rand = "0.7"
rand_core = "0.5"
rand_isaac = "0.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tcod = { version = "0.15", features = ["serialization"] }
typetag = "0.1"
