[package]
name = "innit"
version = "0.0.4"
authors = ["Michael Wagner <wagner.mchl@googlemail.com>"]
license = "MIT License"
edition = "2018"

[dependencies]
dirs = "3.0.1"
cpuprofiler = "0.0.4"
log = "0.4"
num = "0.3.0"
pretty_env_logger = "0.4.0"
rand = "0.7"
rand_core = "0.5"
rand_isaac = "0.2"
rltk = "0.8.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
typetag = "0.1"
