# Check https://rust-lang.github.io/rustup-components-history/ for
# latest nightly availability of rls and rustfmt.

comment_width = 100
wrap_comments = true
enum_discrim_align_threshold = 20
struct_field_align_threshold = 20